### PR TITLE
Add end_date parameter to notebook

### PR DESCRIPTION
**Pull request by devamin**
ready for test : https://colab.research.google.com/drive/1-kcLiys6TpfI1WIRcsLjuWnJuoa_3j86?usp=sharing

### CODE REVIEW

**Comment by dendenski** [comment]
Exchange: Ascendex
pair: FIDA/USDT
range: 8/1/2021 - 9/1/2021
- missing orders 2 on colab notebook
image

**Comment by dendenski** [comment]
Exchange: KuCoin
pair: DIVI/USDT
range: 8/27/2021 - 9/22/2021
- filled trades is available within the range
- the first filled trade date is 9/3/2021
image

**Comment by devamin** [comment]
> Exchange: Ascendex
> pair: FIDA/USDT
> range: 8/1/2021 - 9/1/2021
> 
> * missing orders 2 on colab notebook
>   image


image
After Investigation I noticed a weird behavior from the API, the dates order and filter is not respected in some cases as you can see here this filled order should not be included in this res, this can cause some missing or some duplication.

**Comment by devamin** [comment]
> Exchange: KuCoin
> pair: DIVI/USDT
> range: 8/27/2021 - 9/22/2021
> 
> * filled trades is available within the range
> * the first filled trade date is 9/3/2021
>   image

This is also a weird behavior from the Kucoin API, the start_date should be the closest possible to the real trading start date, if there is more than 5 days of a gap the api return nothing,. 

Here we have 8-27 and the trading started the 9-03 so more than 5 days we will get no result back from the API.  if u set start date to 8-30 it will work fine.

**Comment by devamin** [comment]
@carlolm  @dendenski, I think we can approve this PR because these issues are not caused by the purpose of the PR, and we need to find a workaround for them.

**Review by dendenski — APPROVED** [review]
LGTM, let's just make another PR for issues that found since it is not related to end_date parameter

**Pull request merged**
