### PR TITLE
Feat/add gate client

### PR DESCRIPTION
**Pull request by kadirc**
Re-based and pre-commit applied on Feat/add gate client #11

### CODE REVIEW

**Comment by dendenski** [comment]
image
encountering this error when running the gate_io pnl

**Comment by dendenski** [comment]
> image
> 
> encountering this error when running the gate_io pnl

please ignore, change the git clone on the code to clone the correct branch

**Review by dendenski — APPROVED** [review]
LGTM. done testing
pairs tested:
FEAR_USDT, BATH_USDT

**Review by devamin — APPROVED** [review]
LGTM, thanks @kadirc

**Pull request merged**
