### PR TITLE
Feature/ch17697/update kucoin api for colab notebook

### PR DESCRIPTION
**Pull request by devamin**
fix kucoin. 
colab :https://colab.research.google.com/drive/1bzU8U76nL7SvBWEM_doCSdAqjtJXtYMs?usp=sharing

### CODE REVIEW

**Comment by dendenski** [comment]
need to revise the instruction
image

**Comment by dendenski** [comment]
error running on kucoin
image

**Comment by devamin** [comment]
> error running on kucoin
> image

fixed just the notebook used for test was not up to date.

**Comment by dendenski** [comment]
KuCoin is working now. maybe add more decimal places for pairs that has low price value
image

**Comment by dendenski** [comment]
On ascendex, the trade matches but not sure why the index number is skipping some numbers.
image

**Comment by dendenski** [comment]
getting this error when I run MAPS/USDT pair on ascendex, other pairs are ok.
image

**Comment by dendenski** [comment]
duplicate orders on ascendex, OMI/USDT : 2021-07-13 to 2021-08-13 06:15:25
image
image

**Review by dendenski — APPROVED** [review]
LGTM

**Pull request merged**
