### PR TITLE
fix ascendex adding seqNum to request

### PR DESCRIPTION
**Pull request by devamin**
**What is the issue  :** 
The **ascendex API** not working properly with start_date filter, issues with missing orders, unordered output...

**What I did :**
I added seqNum to the request.

~~But didn't solve it I discovered that there is a real issue, some orders are missing from the API but visible on the website.~~ (dates confusion between UI and API)

### CODE REVIEW

**Comment by devamin** [comment]
Updates : 
* With the seqNum parameter added, the date filter and ordering is solved. 
* I found that #6 the missed orders mentioned by @dendenski was due to that issue, and finally I was able to retrieve all orders there is one single confusion in dates, in the ascendex website the execTime is shown and in the colab I was showing the createTime.

**Comment by dendenski** [comment]
MAPS/USDT
missing 2 orders
date range: 8/1/2021-9/1/2021
image

**Comment by devamin** [comment]
@dendenski sorry how did you test this PR, I am afraid you used the old colab notebook ?

**Comment by devamin** [comment]
If you are testing in colab be sure you are using the right branch 
image

**Comment by dendenski** [comment]
@devamin I'm using this branch
image

**Comment by dendenski** [comment]
I change the branch to this, it is working now.
tested pairs: all OK
OMI/USDT, FIDA/USDT, MAPS/USDT, BTC/USDT
image

**Review by dendenski — APPROVED** [review]
LGTM

**Comment by devamin** [comment]
Great !!

**Pull request merged**
